"""Removed description field from item

Revision ID: a1afa1c909c3
Revises: 13cce330a4c0
Create Date: 2022-04-28 09:08:22.434019

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a1afa1c909c3'
down_revision = '13cce330a4c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('description', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
